export const METHOD_METADATA = 'method'
export const PATH_METADATA = 'path'
export const SCHEMA_METADATA = 'schema'
export const HTTP_CODE_METADATA = '__httpCode__'
export const ROUTE_ARGS_METADATA = '__routeArguments__'
export const RESPONSE_PASSTHROUGH_METADATA = '__responsePassthrough__'
